version: '3'
services:
  # nginx:
  #   image: nginx:stable-alpine
  #   depends_on:
  #     - express-app
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  bunkerized_nginx:
    image: bunkerity/bunkerized-nginx
    restart: unless-stopped
    depends_on:
      - express-app
    ports:
      - 80:8080
      - 443:8443
    # bunkerized-nginx runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    volumes:
      - ./nginx-bunkerized/keys/:/etc/letsencrypt

    command:
      - chmod ugo+rwx /etc/letsencrypt
    environment:
      - SERVER_NAME=www.dasun.ga # replace with your domain
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes
      - USE_PROXY_CACHE=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://express-app:3000/

  express-app:
    build: .
    environment:
      - PORT=3000
